export const Category = {
  CATEGORY_UNSPECIFIED: "CATEGORY_UNSPECIFIED",
  CATEGORY_INCOME: "CATEGORY_INCOME",
  CATEGORY_FOOD: "CATEGORY_FOOD",
  CATEGORY_DAILY_NECESSITIES: "CATEGORY_DAILY_NECESSITIES",
  CATEGORY_HOBBY: "CATEGORY_HOBBY",
  CATEGORY_SOCIAL: "CATEGORY_SOCIAL",
  CATEGORY_TRANSPORTATION: "CATEGORY_TRANSPORTATION",
  CATEGORY_CLOTHING: "CATEGORY_CLOTHING",
  CATEGORY_HEALTH: "CATEGORY_HEALTH",
  CATEGORY_AUTOMOBILE: "CATEGORY_AUTOMOBILE",
  CATEGORY_EDUCATION: "CATEGORY_EDUCATION",
  CATEGORY_SPECIAL: "CATEGORY_SPECIAL",
  CATEGORY_CASH_CARD: "CATEGORY_CASH_CARD",
  CATEGORY_UTILITIES: "CATEGORY_UTILITIES",
  CATEGORY_COMMUNICATION: "CATEGORY_COMMUNICATION",
  CATEGORY_HOUSING: "CATEGORY_HOUSING",
  CATEGORY_TAX_SOCIAL_SECURITY: "CATEGORY_TAX_SOCIAL_SECURITY",
  CATEGORY_INSURANCE: "CATEGORY_INSURANCE",
  CATEGORY_OTHER: "CATEGORY_OTHER",
} as const;

export type Category = (typeof Category)[keyof typeof Category];

export interface Money {
  units: number;
  nanos: number;
}

export interface Transaction {
  id: string;
  date: string;
  title: string;
  amount: Money;
  category: Category;
}

export interface ListTransactionsResponse {
  transactions: Transaction[];
}
