#!/usr/bin/env bash
#MISE description="Apply platform resources (Istio) for local environment"

kubectl apply -f k8s/platform/namespace.yaml
cd k8s/platform && helmfile -e local sync
kubectl label namespace default istio-injection=enabled --overwrite
