#!/usr/bin/env bash
#MISE description="Port forward to Istio IngressGateway"

pkill -f "kubectl port-forward.*istio-ingressgateway" 2>/dev/null
pkill -f "kubectl port-forward.*bff" 2>/dev/null
pkill -f "kubectl port-forward.*web" 2>/dev/null

kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:8080 &>/dev/null &

echo "App: http://localhost:8080"
