// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/boykush/feedhub/server/feed/internal/infra/ent/feed"
	"github.com/boykush/feedhub/server/feed/internal/infra/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	feedFields := schema.Feed{}.Fields()
	_ = feedFields
	// feedDescURL is the schema descriptor for url field.
	feedDescURL := feedFields[1].Descriptor()
	// feed.URLValidator is a validator for the "url" field. It is called by the builders before save.
	feed.URLValidator = feedDescURL.Validators[0].(func(string) error)
	// feedDescTitle is the schema descriptor for title field.
	feedDescTitle := feedFields[2].Descriptor()
	// feed.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	feed.TitleValidator = feedDescTitle.Validators[0].(func(string) error)
	// feedDescCreatedAt is the schema descriptor for created_at field.
	feedDescCreatedAt := feedFields[3].Descriptor()
	// feed.DefaultCreatedAt holds the default value on creation for the created_at field.
	feed.DefaultCreatedAt = feedDescCreatedAt.Default.(func() time.Time)
	// feedDescID is the schema descriptor for id field.
	feedDescID := feedFields[0].Descriptor()
	// feed.DefaultID holds the default value on creation for the id field.
	feed.DefaultID = feedDescID.Default.(func() uuid.UUID)
}
