#!/usr/bin/env bash
#MISE description="Create new migration for collector"
#MISE dir="server/collector"

if [ -z "$1" ]; then
  echo "Usage: mise run db:migrate:diff:collector <migration_name>"
  exit 1
fi

atlas migrate diff "$1" --env local
