#!/usr/bin/env bash
#MISE description="Create new migration for collector"
#MISE dir="server/collector"
#USAGE arg "<name>" help="Migration name (e.g. add_feed_table)"

atlas migrate diff "${usage_name?}" --env local
