#!/usr/bin/env bash
#MISE description="Create new migration for feed"
#MISE dir="server/feed"

if [ -z "$1" ]; then
  echo "Usage: mise run db:migrate:diff:feed <migration_name>"
  exit 1
fi

atlas migrate diff "$1" --env local
