#!/usr/bin/env bash
#MISE description="Build and load web Docker image to kind cluster"
#MISE dir="web"

IMAGE="web-service:latest"

echo "Building image: ${IMAGE}"
docker build -t "$IMAGE" .

echo "Loading image: ${IMAGE}"
kind load docker-image "${IMAGE}" --name foresee

echo "Done!"
